hackernews/config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :articles do
    resources :comments
  end

  get 'articles/index'
  root 'articles#index'

  get '/sessions/new' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'
  post '/:votable_type/:id/vote' => 'votes#create'

end

hackernews/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :votes, as: :votable
  has_many :comments
  belongs_to :poster, class_name: "User"
end

hackernews/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :commenter, class_name: 'User'
  has_many :votes, as: :votable
end

hackernews/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :comments, foreign_key: 'commenter_id'
  has_many :articles, foreign_key: 'poster_id'
  has_many :votes

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def authenticate?(input_password)
    self.password == input_password
  end
end

hackernews/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

hackernews/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hackernews/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.poster_id = 1
    if @article.save
      p @article
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

private

  def article_params
    params.require(:article).permit(:title, :link)
  end

end

hackernews/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @article = Article.find(params[:article_id])
  end

  def new
  end

  def create
    p params
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.commenter_id = 1

    @comment.save
    redirect_to [Article.find(params[:article_id]), :comments]
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to [Article.find(params[:article_id]), :comments]
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

hackernews/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name:
      params[:user][:name])
    if @user.authenticate?(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to articles_path
    else
      @user.errors.add(:name, "name and password do not match")
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to articles_path
  end

end

hackernews/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
   # @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to articles_path
    else
      render 'new'
    end

  end

  def show
    @user = User.find_by(id: session[:user_id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

hackernews/app/controllers/votes_controller.rb
class VotesController < ApplicationController

 def create
    type = params[:votable_type][0...-1].capitalize
    @vote = Vote.new(votable_type: type, votable_id: params[:id], user_id: session[:id])
    p @vote
    @vote.save

    if type == "Comment"
      @article = Comment.find(params[:id]).article
    else
      @article = Article.find(params[:id])
    end

    redirect_to [@article, :comments]

  end

end

hackernews/app/helpers/application_helper.rb
module ApplicationHelper
end

hackernews/app/helpers/articles_helper.rb
module ArticlesHelper
end

hackernews/app/helpers/comments_helper.rb
module CommentsHelper
end

hackernews/app/helpers/sessions_helper.rb
module SessionsHelper
end

hackernews/app/helpers/users_helper.rb
module UsersHelper
end

hackernews/app/helpers/votes_helper.rb
module VotesHelper
end

hackernews/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article && @article.errors.any? %>
    <div>
      <h2> <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

hackernews/app/views/articles/_show.html.erb
<li><%= link_to article.title, article.link %></li>
<li><%= article.poster.name %>
<%= article.votes.count %>
<%= link_to article.comments.count, [article, :comments] %></li>

<% if article.poster_id == session[:user_id] %>
<span>
  <%= link_to 'edit', edit_article_path(article) %>
  <%= link_to 'destroy', article_path(article), method: :delete, data: { confirm: 'Positive?'} %>
</span>
<% else %>
  <%= link_to 'upvote', "/articles/#{article.id}/vote", method: :post %>
<% end %>

hackernews/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

hackernews/app/views/articles/index.html.erb
<h1>Articles!</h1>

<ul>
<% @articles.each do |article| %>
  <%= render partial: 'show', locals: {article: article} %>
<% end %>
</ul>
<p>
<%= link_to "New Article", new_article_path %>
</p>

hackernews/app/views/articles/new.html.erb
<h1>New Article</h1>

  <%= render 'form' %>

hackernews/app/views/comments/_form.html.erb
<%= form_for :comment, url: [article, :comments] do |f| %>

  <% if @comment && @comment.errors.any? %>
    <div>
      <h2> <%= pluralize(@comment.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :content %></br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

hackernews/app/views/comments/_show.html.erb
<li><%= comment.commenter.name %> <%= comment.created_at %></li>
<li><%= comment.content %></li>
<% if comment.commenter.id == session[:user_id] %>
  <%= link_to 'destroy', [Article.find(comment.article_id), comment], method: :delete, data: { confirm: 'Positive?'} %>
<% else %>
  <%= link_to 'upvote', "/comments/#{comment.id}/vote", method: :post %>
<% end %>

hackernews/app/views/comments/index.html.erb
<%= render :partial => 'articles/show', locals: { article: @article } %>

<div class="comment-box">
  <%= render partial: 'form', locals: { article: @article } %>
</div>

<ul>
  <% @article.comments.each do |comment| %>
    <%= render partial: 'show', locals: { comment: comment } %>
  <% end %>
</ul>

hackernews/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackernews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to "Home", "/" %>
  <% if session[:user_id] != nil %>
    <%= link_to "Logout", "/sessions", method: :delete %>
    <%= link_to "User info", user_path(session[:user_id]) %>
  <% else %>
    <%= link_to "Register", new_user_path %>
    <%= link_to "Login", "/sessions/new" %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

hackernews/app/views/users/_form.html.erb
<%= form_for :user, url: users_path do |f| %>

  <% if @user && @user.errors.any? %>
    <div>
      <h2> <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

hackernews/app/views/users/new.html.erb
<h1>Register!</h1>

<%= render 'form' %>

hackernews/app/views/users/show.html.erb
<h1><%= @user.name%>'s page</h1>

<h4><%= @user.name %>'s Articles</h4>
<ul>
  <% @user.articles.each do |article| %>
    <%= render :partial => 'articles/show', locals: { article: article } %>
  <% end %>
</ul>

<h4><%= @user.name %>'s Comments</h4>
<ul>
  <% @user.comments.each do |comment| %>
    <%= render :partial => 'comments/show', locals: { comment: comment } %>
  <% end %>
</ul>